# Generated by Django 5.1.4 on 2025-02-20 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_passwordreset_expires_at_profile_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 21, 2, 34, 56, 881867)),
        ),
    ]
